name: pijetin
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bottom_sheet: ^3.1.2
  calendar_date_picker2: ^0.5.2
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.6
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_google_map_polyline_point: ^0.0.1
  flutter_local_notifications: ^15.1.0+1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.8.4
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  get_storage: ^2.1.1
  google_maps_flutter: ^2.3.1
  google_sign_in: ^6.1.4
  google_static_maps_controller: ^1.0.0
  http: ^1.1.0
  image_picker: ^1.0.0
  intl: ^0.18.1
  loading_overlay: ^0.3.0
  mockito: ^5.4.2
  qr_flutter: ^4.1.0
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppin/Poppins-Bold.ttf
        - asset: assets/fonts/poppin/Poppins-SemiBold.ttf
        - asset: assets/fonts/poppin/Poppins-Medium.ttf
        - asset: assets/fonts/poppin/Poppins-Regular.ttf
        - asset: assets/fonts/poppin/Poppins-Light.ttf
